name: Format

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: dev

jobs:
  pre-commit:
    name: Python Code Format
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
